'use client'

import React, { useState } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { AuthProvider } from '../context/AuthContext'
import NavBar from './navBar';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <AuthProvider>
          <NavBar></NavBar>
          <main className={inter.className}>{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
