import './globals.css'
import { Inter } from 'next/font/google'
import { AuthProvider } from '../context/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <AuthProvider>
        <body>
          <nav className="bg-gray-800 p-6">
            <div className="flex justify-between items-center">
              <a href="/" className="text-white text-2xl font-medium">Shift Table</a>
              <div className="flex">
                <a href="/" className="text-white text-lg mr-4">Home</a>
                <a href="/contact" className="text-white text-lg mr-4">Contact</a>
                <button id="logout-btn-auth" className="text-white text-lg mr-4 font-bold rounded-full hover:bg-slate-700">Logout</button>
              </div>
            </div>
          </nav>
          <main className={inter.className}>{children}</main>
        </body>
      </AuthProvider>
    </html>
  )
}
